class Config(object):

    # get a token from @BotFather
    BOT_TOKEN = "6043283784:AAHLV11M9g3gaDj5dE-Sr5fKhSCd8CT-lOc"

    # Get these values from my.telegram.org
    API_ID = 7143337
    API_HASH = "1afa55a5f3bf7058c843d1b290f79c49"
# OPTIONAL CONFIG
AUTHORIZED_USERS=
DATABASE_URL=
IS_TEAM_DRIVE=
USE_SERVICE_ACCOUNTS=
DOWNLOAD_DIR=
STATUS_UPDATE_INTERVAL=
TELEGRAPH_ACCS=
INDEX_URL=
ARCHIVE_LIMIT=
CLONE_LIMIT=
TOKEN_JSON_URL=
ACCOUNTS_ZIP_URL=
DRIVE_LIST_URL=
GDTOT_CRYPT=
